### ISSUE TITLE
getting the MessageID

### ISSUE THREAD

**Issue by conanite** [wildbit/postmark-gem#100]
Hello,

I'm using this gem alongside postmark-rails.

In gem version 1.15, in api_client.rb, you have this line in the `update_message` method:

`message['Message-ID'] = response['MessageID']`

the latest version however has this:

`message['X-PM-Message-Id'] = response['MessageID']`

Using ActionMailer, a call to `mail.message_id` used to return the one true postmark message ID, but now returns the old 'Message-ID' header, which rails' ActionMailer sets to its own generated message ID. 

So `mail.message_id` is no longer useful for tracking the message lifecycle (bounces for example) - postmark doesn't know anything about the ActionMailer-generated message id.

I've fixed my code to look for the 'X-PM-Message-Id' header instead of calling #message_id, but it might be useful for other users to have this slightly surprising behaviour explained somewhere?

cheers

**Comment by hvilloria** [comment]
Same issue here!

**Comment by igorpan** [comment]
We're experiencing the same issue.

**Comment by DylanFM** [comment]
+1 this has tripped us up. We would have appreciated it if this change had some more information alongside it. Such as an example for retrieving the real message ID, if you had been using `#message_id` previously.

**Comment by ibalosh** [comment]
Hi guys, 
thank you for reporting this and sorry for this taking so long to handle. We have updated wiki to fix this confusion.
