### ISSUE TITLE
Upcoming Postmark TLS Changes

### ISSUE THREAD

**Issue by mgomes** [wildbit/postmark-gem#102]
Hello,

Does this gem already support (or will support) the upcoming changes to the Postmark API? [This email](https://postmarkapp.com/updates/upcoming-tls-configuration-changes-for-api-users-action-may-be-required) just went out, but it's not clear if official clients such as this one are ready to go.

Thanks for your help!

**Comment by tomazy** [comment]
You need to make sure that your ruby/openssl version supports TLS version greater than 1.0 which should be the case unless you're using a very old version of ruby or openssl - support for TLS 1.1 & 1.2 was added back in 2012: https://github.com/ruby/ruby/commit/060184c347822b11dff3db6bef915c04a564c4e4 .

The best way to check if you're safe is to connect to the new temporary endpoint and send an email:

```ruby
require 'postmark'

client = Postmark::ApiClient.new(SERVER_TOKEN, host: 'api-ssl-temp.postmarkapp.com')
client.deliver(from: ..., to: ...., text_body: 'test')
```

In case of any issues with ruby and SSL I recommend this troubleshooting guide from the bundler project: https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#tls-10-and-11-are-deprecated .

**Comment by mgomes** [comment]
Thanks @tomazy :+1:

**Comment by elbrunof** [comment]
You may need to add `http_ssl_version: :TLSv1_2` to `ApiClient`: 
```ruby
client = Postmark::ApiClient.new(POSTMARK_API_TOKEN, host: 'api-ssl-temp.postmarkapp.com', http_ssl_version: :TLSv1_2)
```

In case you use `postmark-rails`, add `http_ssl_version: :TLSv1_2` to your application config file:

```ruby
config.action_mailer.postmark_settings = {
  api_token: ENV['POSTMARK_API_TOKEN'],
  http_ssl_version: :TLSv1_2,
}
 ````

**Comment by beder** [comment]
> You may need to add `http_ssl_version: :TLSv1_2` to `ApiClient`:
> 
> ```ruby
> client = Postmark::ApiClient.new(POSTMARK_API_TOKEN, host: 'api-ssl-temp.postmarkapp.com', http_ssl_version: :TLSv1_2)
> ```
> 
> In case you use `postmark-rails`, add `http_ssl_version: :TLSv1_2` to your application config file:
> 
> ```ruby
> config.action_mailer.postmark_settings = {
>   api_token: ENV['POSTMARK_API_TOKEN'],
>   http_ssl_version: :TLSv1_2,
> }
> ```

Please note that `http_ssl_version` is needed only in postmark gem versions prior to v1.2.3. Version 1.2.3 removes TLSV1 as the default SSL version and lets the HTTP client negotiate the SSL version.

[Method: HTTPClient::SSLConfig#ssl_version](https://www.rubydoc.info/gems/httpclient/2.4.0/HTTPClient%2FSSLConfig:ssl_version)

See: 529e9db

**Comment by DylanFM** [comment]
I may be mistaken here, but I ran into an exception when following the testing steps above. Despite the bundler curl test passing 👌. After updating our postmark(-rails) gem test email sent fine. 

Just in case someone runs into this exception and thinks they need to fix other things - check that your postmark gem is up to date.

Before gem update:

```
client = Postmark::ApiClient.new k, host: 'api-ssl-temp.postmarkapp.com'
=> #<Postmark::ApiClient:0x000055daf3263260 ...>>>
client.deliver(from: '...', to: '...', text_body: 'testing api-ssl-temp.postmarkapp.com')
Traceback (most recent call last):
        1: from (irb):14
OpenSSL::SSL::SSLError (SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello) 
```

After update:

```
client.deliver(from: '...', to: '...', text_body: 'testing api-ssl-temp.postmarkapp.com')
=> {:to=>"...", :submitted_at=>"2021-02-25T13:50:46.4864111Z", :message_id=>"...", :error_code=>0, :message=>"OK"}
```

**Comment by jshow** [comment]
after upgrading to the latest postmark gems, I had to install openssl gem, install libssl-dev package and recompile the ruby binary - all good now
