### ISSUE TITLE
`deliver_messages_with_templates` produces invalid JSON

### ISSUE THREAD

**Issue by mikecx** [wildbit/postmark-gem#104]
When using `deliver_messages_with_templates` the message should be formatted with a { "Messages": [] } wrapper as described here: https://postmarkapp.com/api-explorer#!/Sending_API/sendEmailBatchWithTemplates but when using the gem, the Messages wrapper is left off and results in a `Postmark::ApiInputError: Received valid, but incompatible JSON input.` error.

Sample code:

```ruby
messages = []
subscription.each do |subscription|
  messages << UserMailer.subscriptions(email: subscription.email)
end

client = Postmark::ApiClient.new(POSTMARK_SERVER_TOKEN)
client.deliver_messages_with_templates(messages)
```

Using the Postmark API explorer with the generated body in the API call fails. Wrapping it with `"Messages":` is successful.

**Comment by mikecx** [comment]
Updating https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/api_client.rb#L84 to `data = serialize(:Messages => batch.map { |m| m.to_postmark_hash })` fixes the issue but I haven't had any luck getting `rake spec` to run green so I haven't been able to push up a PR.

**Comment by tomazy** [comment]
Thanks @mikecx for reporting. It's seems to be a bug indeed. We'll try to look into it and provide a fix asap.

**Comment by tomazy** [comment]
@mikecx the issue has been fixed. Please upgrade the gem to the version 1.21.4. Thanks again for reporting and for drafting a pull request 🤘
