### ISSUE TITLE
Template Alias in ApplicationMailer

### ISSUE THREAD

**Issue by leoplct** [wildbit/postmark-gem#106]
We have created the "welcome" template from Postmark UI and I want to send it using Rails Active Mailer. 
I've tried with this code below but it sends the rails view mail.

`UserMailer.with(user: User.find(1)).welcome.deliver_now`

```
class UserMailer < ApplicationMailer
   def welcome
        mail(
            :to      => 'info@example.com',
            :from    => 'info@example.com',
            :alias   => 'welcome',
        )
 end
end
```

I know I could use this 
```
def  welcome
  client = Postmark::ApiClient.new('XXX')
  client.deliver_with_template(
              {:from=>"info@example.com",
              :to=>"info@example.com",
              :template_alias=>"welcome",
              :template_model=>
                  {"product_name"=>"product_name_Value",
                  "product_url"=>"product_url_Value",
                  "company_name"=>"company_name_Value",
                  "company_address"=>"company_address_Value"}}
          )
end
```

but I have to use the native mail() method to prevent a send if certain actions have been satistied (e.g. not sending twice)
```
if check_logs_already_sent
  mail.perform_deliveries = false
end

```

**Comment by ibalosh** [comment]
Hi @leoplct 

I would suggest checking out Rails [wiki](https://github.com/wildbit/postmark-rails/wiki/Using-Postmark-Templates) on how to use templates with action mailer. Will close here the issue, since it's not Postmark gem related. If you encounter issues wit templates on Rails ActionMailer, please create a ticket on Postmark Rails gem.

**Comment by leoplct** [comment]
Thank you. I haven't found it. I suggest adding a link to it in the main Readme.md

**Comment by ibalosh** [comment]
Hi @leoplct 

you are welcome, we will check that out. We use main readme mainly for short descriptions while more detailed library usage is explained through wiki 

Igor
