### ISSUE TITLE
get_bounces not retrieving all bounces

### ISSUE THREAD

**Issue by estani** [wildbit/postmark-gem#115]
Not sure if this is a problem in the API or my comprehension of it.

I'd expect `get_bounces` to retrieve all bounces, it does not, though it retrieve "some".
If I use `dump_suppressions` then I see a lot of HardBounces, shouldn't HardBounces be retrieved from `get_bounces` too?
Or is there a special case?

**Comment by ibalosh** [comment]
Hi @estani 

`get_bounces` or any other call that can retrieve large amount of data in array is limited. The library itself limits this to count of 30, which can be seen in https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/client.rb .

However, you can do a call like: `client.get_bounces(count: 100)` which will return 100 bounces. The maximum allowed number by API is 500. If you try to retrieve more than that at once, you will get a limitation error from API. 

We suggest filtering requests with one of querystring parameters described [here](https://postmarkapp.com/developer/api/bounce-api#bounces) in our developer docs to retrieve specific bounces and reduce number of bounces to search.

You can set those parameters in your calls with something like this:  `client.get_bounces(emailFilter: "nothing+23120782@bounces.example.com", inactive: true)`.

Let us know if that works and if you will need more help with library usage feel free to contact our support.

Thanks

**Comment by estani** [comment]
Ok, I had the feeling it was returning even less than 10. We also used filtering, but it didn't match either.

Furthermore the previous way of reactivating bounces (`activate_bounce/:bounce_id`), does not work with those, as it is impossible to retrieve their id.

But from your mail I understand, that `get_bounces` should return the same data as `dump_suppresions`, even if differently paginated. So our current approach should work just fine.

**Comment by ibalosh** [comment]
Hi @estani 

I suggest checking out the calls in [developer docs](https://postmarkapp.com/developer/api/bounce-api) for bounces and [suppressions too](https://postmarkapp.com/developer/api/suppressions-api).

Suppressions are different from Bounces. 

Bounces endpoint is an older endpoint which will return all bounces for your server in paginated (count) manner. These are also bounces which do not deactivate email addresses (like soft bounce, smtp api error etc). Bounces endpoint will not return very old bounce addresses, we suggest suppressions for that.

Suppressions though will return only inactive email addresses which are suppressed. They do not contain addresses of any active addresses. 

I suggest using dump suppressions with delete suppressions to activate email addresses. If you use get bounces to get addresses, you can use activate bounces method to reactivate.

**Comment by estani** [comment]
Thanks @ibalosh, that clarifies things.

We only need our users to be able to reactivate the own emails in their organizations, if they got blocked (sometimes, the email addresses are created after the first time a mail is sent, without the knowledge of the user, causing the mentioned suppression).
So `suppressions` seem to be the endpoint we need to be using. Thanks.

**Comment by ibalosh** [comment]
You are welcome @estani
