### ISSUE TITLE
Describe the process of testing with postmark gem

### ISSUE THREAD

**Issue by Valve** [wildbit/postmark-gem#42]
When writing tests, it's useful to be able to configure a gem not to perform actual network interactions.

```
Postmark.test_mode = true
```

Also, ideally, postmark should add a set of RSpec helpers to verify that a certain email was sent in test mode, for example:

```
expect(Postmark).to have_sent_email(subj).with_body(body).with_recipient(s)(arr_of_recipients)
```

Please add the guidelines for how to do it to Readme or the documentation.

**Comment by ibalosh** [comment]
Hi, 

test mode is something we can't provide due our API architecture. However, we provided comprehensive integration testing [wiki article](https://github.com/wildbit/postmark-gem/wiki/Integration-testing) which should help getting testing going on your side.

Igor
