### ISSUE TITLE
Stop forcing title case for custom headers

### ISSUE THREAD

**Issue by jptoto** [wildbit/postmark-gem#47]
We change the casing of incoming custom headers to capital-case but this modifies what the user is expecting. 

Case in point, x-custom-header becomes X-Custom-Header.

https://github.com/wildbit/postmark-gem/blob/7ea6afc10ad5a962f3de54fc48044d394e56e464/lib/postmark/message_extensions/mail.rb#L35

**Comment by ibalosh** [comment]
Title case is not forces anymore, from revision 1.18.0
