### ISSUE TITLE
Any plans to support Rails 5?

### ISSUE THREAD

**Issue by acorncom** [wildbit/postmark-gem#51]
I'm currently using Postmark for a client and am quite happy using it.  Was wondering if Rails5 compatibility was slated here, as we're starting a new project that will be requiring it ...

Thanks!

**Comment by temochka** [comment]
Hi! The `postmark` gem does not depend on Rails, so it should work fine in any Ruby app. As for the [postmark-rails](https://github.com/wildbit/postmark-rails) gem, unfortunately we haven’t got a chance to test it against ActionMailer 5.0 yet. Thanks for a reminder, I’m now going to add the latest release candidate of the `actionmailer` gem to our CI config next week.
