### ISSUE TITLE
Support offline mode

### ISSUE THREAD

**Issue by ditsara** [wildbit/postmark-gem#54]
Is there a way to have Postmark::ApiClient do everything except actually perform the API call, for testing / debugging purposes?

Example from python-postmark: https://github.com/themartorana/python-postmark/blob/master/postmark/core.py#L420

**Comment by temochka** [comment]
There is currently no debug (or offline) mode in the gem, but it’s possible to use the [test API token](http://developer.postmarkapp.com/developer-send-api.html) (`POSTMARK_API_TEST`) to instruct the API not to send a submitted email. This approach is platform-independent.

**Comment by ibalosh** [comment]
Hi,

unfortunatelly there is no easy way to add debug mode to the gem due the way our API works, however we provided a comprehensive integration testing [wiki article](https://github.com/wildbit/postmark-gem/wiki/Integration-testing) which should allow easy implementation of offline mode testing.
