### ISSUE TITLE
How to deal with `execution expired` and `Connection reset by peer - SSL_connect` RuntimeErrors

### ISSUE THREAD

**Issue by Hirurg103** [wildbit/postmark-gem#59]
Recently I started to notice that we are getting `RuntimeError: Connection reset by peer - SSL_connect` and `RuntimeError: execution expired` errors quite often. In this case our users are missing emails

I know that postmark gem have [mechanism to retry Delivery Errors](https://github.com/wildbit/postmark-gem/blob/f25565df3ff264c3342f4b1e07a3280bc2fda47e/lib/postmark/client.rb#L38-L47). But delivery error is a StandardError but not a RuntimeError so retry mechanism doesn't work for `execution expired` and `Connection reset by peer - SSL_connect`

How should we handle these errors in our application? Do we need to rescue these runtime errors ourselves and retry the delivery in our codebase? Or it will be better to handle this kind of errors in the posmark gem itself?

What do you think, guys? Thanks!

**Comment by Hirurg103** [comment]
Currently we are having the following code in our codebase:
```ruby
# lib/postmark/connection_error.rb
class Postmark::ConnectionError < RuntimeError

  def self.===(exception)
    exception.message =~ /^execution expired$/ ||
      exception.message =~ /^Connection reset by peer - SSL_connect$/
  end

end

# the code which sends emails
with_retries do
  @client.deliver_messages(@messages)
end

def with_retries
  yield
rescue Postmark::ConnectionError
  retries = retries ? retries + 1 : 1
  if retries < 3
    retry
  else
    raise
  end
end
```

**Comment by temochka** [comment]
Hi @Hirurg103! Sorry this has stayed without a response for a while. What you’re doing is indeed the best way to handle network errors at the moment.

In general, our client libraries don’t make any assumptions about your execution model, so the burden of handling network errors is therefore on the user. We don’t have plans to change that part. You might want to increase your `http_read_timeout` and `http_open_timeout` settings if you’re getting too many timeouts. Also, please reach out to our [support](https://postmarkapp.com/contact) if all these connection errors are giving you too much trouble. There are some tests we can run to figure out what’s causing them.

That said, I’m not happy with how Postmark obscures the network exceptions making you have to do all this fragile regexp matching. I’m going to look into adding a more specific `NetworkError` class, and I’ll test that timeouts are also wrapped into an appropriate `TimeoutError`.

This is also related to #53.

**Comment by temochka** [comment]
Ok, starting with version `1.11.0`, we now have more useful error types and a detailed example of error handling in the [README](https://github.com/wildbit/postmark-gem/tree/v1.11.0#error-handling).
