### ISSUE TITLE
New Tag

### ISSUE THREAD

**Issue by mchaisse** [wildbit/postmark-gem#62]
Hi! Looks like the last release was made on November 28, 2016 (v1.10.0).
Would it be possible to have a new tag? :)

**Comment by temochka** [comment]
Sorry about that. Not sure what went wrong with our release scripts for `v1.10.0`. We’re planning to release `v1.11.0` this week, which should fix the issue.

**Comment by temochka** [comment]
Ok, `v1.11.0` is live on Rubygems now. Give it a try! See the [CHANGELOG](https://github.com/wildbit/postmark-gem/blob/v1.11.0/CHANGELOG.rdoc) for details.
