### ISSUE TITLE
Best way to test email sent success

### ISSUE THREAD

**Issue by Fjohn666** [wildbit/postmark-gem#73]
Hello,
I would like to know the best way to test if an email has been sended or not. I see two way to do this : 

- the response of the send method
- the bounce endpoint with the filter "email"

what is the best way to be sure that the email has been sended and there is an error ?

thanks for your help

**Comment by temochka** [comment]
Hi @Fjohn666, this GitHub is for bug reports only, please contact our support at [support@postmarkapp.com](mailto:support@postmarkapp.com) or through our [form](https://postmarkapp.com/contact).
