### ISSUE TITLE
Suggestions for improving usability during testing

### ISSUE THREAD

**Issue by rgalanakis** [wildbit/postmark-gem#77]
Hi folks! I have really liked using the API for the most part.
But the main issue I had while integrating was around testing,
both at the unit level and then for staging/integration tests.

## Unit testing

When unit testing code that hits libraries with 3rd party APIs,
I try to mock at the HTTP level, usually with webmock.
This ensures I'm calling the library correctly,
and also helps me understand the service better,
by exposing me to actual requests and responses.

Unfortunately, it was difficult to get this working for Postmark,
or at least difficult to track down why it wasn't working.
Postmark's client internally creates a new Net::HTTP instance,
rather than using using default clients.

I am a fan of that design, but it unfortunately means that
if your tests end up creating a Postmark client before Webmock
is set up, you get a client that Webmock can't actually patch.

It took me a while to realize that my unit tests were actually
hitting Postmark's live API! I had to change my code around
so I create a new Postmark client for each call,
rather than using a global client.

I'm not sure what the right answer is- I can think of a bunch
of different solutions and none is obviously 'right'
Ie, deferring creation of stuff until first call has
downsides too! like lack of predictability/side effects.
But I can say that the current UX can/should be improved.

Also, it may be nice to have some webmock-style unit tests
in your repo itself, to make it easier to grab
example request and response bodies for our own tests.

## Integration tests

The other testing issue I had was around integration tests.
I have been using Sendgrid (and Mailgun before that),
so I am forgiving that there is not an iron-clad dev environment.
However, the lack of any opinion or information about
a dev environment meant I needed to figure out how to do this myself.
Eventually I stumbled up on the 'api test key' trick
in the Sendgrid migration guide. Without it, I'm not sure what
I would have done.

The 'api test key' is a nice but it's sort of the minimum, and doesn't really cover the integration test use case.
What would be really nice is to have a way to blocklist/allowlist
certain email addresses in Postmark (nb I have this set up in our app code but I like the redundancy of the service provider having ti as well).

And also, a way to have an account set up for testing,
so we can send emails from staging environments
that is separate from our production account.
With SendGrid, I ended up having a second 'test' account.
With Postmark, I can do the same, except the account verification stuff
makes me feel like doing that is a violation of the system.

In any case, the thing that would have been most helpful would
have been some consolidated opinion and information about
how you suggest customers handle their staging environments,
even if you don't have a good technical solution for it. Same, I guess, for unit tests. There are great docs in general, and the only thing missing I found was clear documentation about unit and integration testing code that uses your gem.

Hope that's helpful. Thank you!

**Comment by rianvdm** [comment]
Hey @rgalanakis, thanks for this feedback, it's really useful. We have a pretty big list of things we know we need to do to improve developer evaluation and testing, and many of the things you mentioned are on that list. So, in short, we agree!

As for integration testing, we usually encourage people to create separate Servers within their accounts for each environment. We often see Staging and Production servers within accounts. You can push templates from one server to another, so this ends up being a pretty good solution for most people.

@atheken Do you have thoughts/idea on any of Rob's other feedback?

**Comment by ibalosh** [comment]
Hi @rgalanakis 

our team was thinking a lot about the possible solutions and easiest ways to do testing and integration testing with Ruby gem. As a result, we created an [integration testing wiki article](https://github.com/wildbit/postmark-gem/wiki/Integration-testing) which should help get testing going on your side and integrate Ruby library with ease.

Let us know what you think about that process,
Thanks
Igor

**Comment by rgalanakis** [comment]
Hi Igor- that article is great, thank you! I especially appreciate how you spent extra effort doing a VCR/webmock walkthrough for your specific use-case and responses (not that it's different from other use-cases, it's just extra helpful). Between this article and the test token trick, we should be in good shape.

A couple minor suggestions:
- The api token in your captured VCR response doesn't match the one used in the Ruby code at the top of the article. And many folks may not want their token checked in, though it may be okay (tbh I do not usually use VCR cassettes, so I don't know what's idiomatic).
- Mention the test token feature in this article. I don't know if the rest of the docs have been changed, but I recall it being difficult to find, and it'd be good to mention it around integration testing, IMO.

**Comment by ibalosh** [comment]
Hi @rgalanakis 

You are welcome, thank you for the suggestions! 
We have updated the article which should fix both issues.

Thanks!
