### ISSUE TITLE
Enable finding domain resource by domain name

### ISSUE THREAD

**Issue by matthutchinson** [wildbit/postmark-gem#79]
### Context

At Freeagent we make extensive use of the domains endpoint, to keep our custom sender email addresses in-sync with sender signatures at Postmark.

This usually works well, but we occasionally get into a situation where they get out of sync. I.e. we've lost the reference to Postmark's domain id (by someone successfully deleting the custom sender email at Freeagent) but the call to destroy the domain/sender sig at Postmark failed (sometimes caused by a Postmark API timeout error that is beyond our control).

In order to resolve this (when a customer inevitably wants to re-add this custom sender email), our support team must visit the Postmark dashboard, manually find the domain and delete it from there.

### Suggestions

I can suggest two ideas to allow us to programmatically do this:

1) When your 512 error is returned on creating a domain, include the domain id in the error somewhere (an attribute or within the message so it can be parsed out).

2) Allow finding a domain resource by domain id. That way we can look for it and delete it through the API knowing its id.  (I realise we could do this by traversing the entire domain list endpoint and searching, but that seems very inefficient given the large number of domains we have).

Finally a question: Is it possible for a domain / sender signature to be created and persisted at Postmark, but the API request times out?

---

I realise this is not an issue with this gem, but suggestions for your APIin general.  Apologies if this is not the right place for that.

**Comment by ibalosh** [comment]
Hi @matthutchinson 

sorry for taking so long to answer, the ticket slipped through and we missed it. I will forward the question to the team, and see what we could do to improve the domain request endpoint experience.

Igor

**Comment by ibalosh** [comment]
Hi @matthutchinson 

we added domain search improvements to our request list. We can't give an estimate about it though, since it's not in high demand.

Regrding timeouts, unfortunately we can't know at the time they happen whether request succeded and give more details about it. However if you do see this frequently, please let our support know.

I will close the ticket, since it's not gem related, however if you do have any questions and suggestion related to Postmark or API, feel free to contact our top notch support crew.

Igor

**Comment by matthutchinson** [comment]
Thanks @ibalosh, will do 👍

**Comment by wnm** [comment]
>     1. When your 512 error is returned on creating a domain, include the domain id in the error somewhere (an attribute or within the message so it can be parsed out).

Just came to say, that I too, would find it helpful if the 512 error would return the domain id!
