### ISSUE TITLE
Make it easier to rescue errors pertaining to 'To' address

### ISSUE THREAD

**Issue by mloughran** [wildbit/postmark-gem#87]
Problem: Users sometimes mistype emails addresses and we'd like to easily handle the resultant errors returned from the postmark API.

Currently one has to handle (a fairly generic) API error code 300 and manually check the error message for a string such as `Invalid 'To' address: 'foo@bar'` to handle invalid 'To' addresses. As a fairly core domain concept for Postmark I was surprised not to find a dedicated code for this case.

	irb(main):033:0> err
	=> #<Postmark::ApiInputError: Invalid 'To' address: 'foo@bar'.>
	irb(main):034:0> err.status_code
	=> 422
	irb(main):035:0> err.error_code
	=> 300
	irb(main):036:0> err.message
	=> "Invalid 'To' address: 'foo@bar'."

It would be great if the API docs could make it clearer that 300 this is the correct error code for this case to avoid experiment driven development. From the docs at https://postmarkapp.com/developer/api/overview#error-codes:

* **300 — Invalid email request** Validation failed for the email request JSON data that you provided.
* **522 — Value for field is invalid**. Value might be an invalid email address or domain. View the Message property of the response for details. *[this is the one I'd guess from the docs]*

The https://github.com/wildbit/postmark-gem/wiki/Error-Handling page could be better. Its suggestion for `ApiInputError` is "Look up the error code and resolve the problem in your app", but invalid email addresses aren't typically an app problem.

A potential solution in this gem would be to add a custom error (following the same pattern as `InactiveRecipientError` in https://github.com/wildbit/postmark-gem/blob/master/lib/postmark/error.rb#L55) to make handling this particular scenario easier. Currently I end up with the following in application code:

```ruby
def send_email
  yield
rescue Postmark::InactiveRecipientError
  raise CustomError
rescue Postmark::ApiInputError => e
  if e.error_code == 300 && e.message.match(/^Invalid 'To' address:/)
    raise CustomError, e.message
  elsif e.error_code == 300 && e.message.match(/^Error parsing 'To':/)
    raise CustomError, e.message
  else
    raise
  end
end
```

**Comment by ibalosh** [comment]
Hi,

we updated the gem so from version 1.21.6 you can use custom Postmark::InvalidEmailAddressError to rescue for invalid email addresses
