### ISSUE TITLE
Missing pattern in InactiveRecipientError.parse_recipients

### ISSUE THREAD

**Issue by FabricioFFC** [wildbit/postmark-gem#89]
I have the following scenario: An e-mail has a valid `cc`, but the `to`recipient is invalid and it was marked as `hard bounced` before. In this scenario postmark API returns: `Message OK, but will not deliver to these inactive addresses: some-hard-bounced-email@postmark.com`

I've found in this issue https://github.com/wildbit/postmark-gem/issues/53#issuecomment-401928511, that I can use `Postmark::InactiveRecipientError.parse_recipients(response[:message])` to get the failed recipients. But the [`PATTERNS`](https://github.com/wildbit/postmark-gem/blob/a502eb79e5332c8ed54c1a3a437be0eba4c71e0e/lib/postmark/error.rb#L74) doesn't have a pattern that matches with that message.

A possible solution would be to include a new pattern, but it's very similar with `/these inactive addresses: (.+?)\. Inactive/`, so maybe the error is to have two similar messages.

**Comment by ibalosh** [comment]
Hi @FabricioFFC 

we have released a version 1.21.7 which should resolve this issue

**Comment by marshallds** [comment]
This is still not resolved (using version 1.22.0) for the following message:
> "You tried to send to recipient(s) that have been marked as inactive. Found inactive addresses: invalid@example.com. Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression."

The solution seems to be to add the following pattern: `/^Found inactive addresses: (.+?)\. Inactive/.freeze`
