### ISSUE TITLE
Rails gem should use `message_stream` when supplied

### ISSUE THREAD

**Issue by atheken** [wildbit/postmark-gem#90]
It _appears_ that we map a hash into a postmark payload.

However, this doesn't map `message_stream`, when provided, and so the gem doesn't appear to support message streams:

https://github.com/wildbit/postmark-gem/blob/b1d765e528e76f11ed50eb33c6544946175aacb3/lib/postmark/helpers/message_helper.rb#L25

**Comment by nickhammond** [comment]
Fixed via #91.
